baseurl = "https://glumia.dev/"
author = "Giuseppe Lumia"
title = "glumia's blog"
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
pluralizelisttitles = false
enableRobotsTXT=true
canonifyurls = true

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
copyright = "CC BY-SA 4.0 © 2021 Giuseppe Lumia"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "logo_glumia_512.jpg"
faviconfile = "favicon-32x32.png"
github = "glumia"
email = "gius@glumia.dev"
linkedin = "glumia"
twitter = "glumia8"
posts_navigation = true
small_banner_logo = true
lang = "en"
latestpostcount = 5

[markup]
  [markup.highlight]
    style="tango"

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5
