name: CI

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d
        with:
          hugo-version: '0.136.2'
        
      - name: Build
        run: hugo --minify
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: glumia/glumia.github.io
          publish_branch: master
          publish_dir: ./public
